# More excercises on numpy

In [8]:
import numpy as np 

### Reshaping

<div class="alert alert-success">
<b>EXERCISE- Reshaping</b>:

 <ul>
  <li>Create a numpy array with random variables of shape 8. Reshape the previous array to have a new array of size (2, 2, 2)</li>
  
</ul>
</div>

In [12]:
A = np.arange(8)
A.shape
print(A)

[0 1 2 3 4 5 6 7]


In [17]:
B = A.reshape((2,2,2))
print(B.shape)
print(B)

(2, 2, 2)
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


### Broadcasting
Broadcasting applies these three rules:

* If the two arrays differ in their number of dimensions, the shape of the array with fewer dimensions is padded with ones on its leading (left) side.

* If the shape of the two arrays does not match in any dimension, either array with shape equal to 1 in a given dimension is stretched to match the other shape.

* If in any dimension the sizes disagree and neither has shape equal to 1, an error is raised.

Note that all of this happens without ever actually creating the expanded arrays in memory! This broadcasting behavior is in practice enormously powerful, especially given that when NumPy broadcasts to create new dimensions or to 'stretch' existing ones, it doesn't actually duplicate the data. This can save lots of memory in cases when the arrays in question are large. As such this can have significant performance implications.</li>
  

<img src="./images/broadcasting.png">

<div class="alert alert-success">
<b>EXERCISE- Reshaping</b>:

 <ul>
  <li>Replicate the above exercises. In addition, how would you make the matrix multiplication between 2 matrices</li>
  
</ul>
</div>


.

In [27]:
np.arange(3) + np.array([5])

array([5, 6, 7])

In [23]:
np.ones((3,3))+ np.arange(3)

array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.]])

In [26]:
np.array([[0], [1], [2]]) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [28]:
X = np.random.random((1,3))
Y = np.random.random((3,5))

In [30]:
X*Y

ValueError: operands could not be broadcast together with shapes (1,3) (3,5) 

In [31]:
np.dot(X,Y)

array([[ 1.47709167,  1.3336312 ,  0.80640051,  0.95219267,  0.9666394 ]])

In [32]:
X@Y

array([[ 1.47709167,  1.3336312 ,  0.80640051,  0.95219267,  0.9666394 ]])

### Views on Arrays

NumPy attempts to not make copies of arrays. Many NumPy operations will produce a reference to an existing array, known as a "view", instead of making a whole new array. For example, indexing and reshaping provide a view of the same memory wherever possible.

In [34]:
arr = np.arange(8)
arr_view = arr.reshape(2, 4)

# Print the "view" array from reshape.
print('Before\n', arr_view)

# Update the first element of the original array.
arr[0] = 1000

# Print the "view" array from reshape again,
# noticing the first value has changed.
print('After\n', arr_view)

Before
 [[0 1 2 3]
 [4 5 6 7]]
After
 [[1000    1    2    3]
 [   4    5    6    7]]


What this means is that if one array (`arr`) is modified, the other (`arr_view`) will also be updated : the same memory is being shared. This is a valuable tool which enables the system memory overhead to be managed, which is particularly useful when handling lots of large arrays. The lack of copying allows for very efficient vectorized operations.

Remember, this behaviour is automatic in most of NumPy, so it requires some consideration in your code, it can lead to some bugs that are hard to track down. For example, if you are changing some elements of an array that you are using elsewhere, you may want to explicitly copy that array before making changes. If in doubt, you can always copy the data to a different block of memory with the copy() method.

For example:


In [35]:
arr = np.arange(8)
arr_view = arr.reshape(2, 4).copy()

# Print the "view" array from reshape.
print('Before\n', arr_view)

# Update the first element of the original array.
arr[0] = 1000

# Print the "view" array from reshape again,
# noticing the first value has changed.
print('After\n', arr_view)

Before
 [[0 1 2 3]
 [4 5 6 7]]
After
 [[0 1 2 3]
 [4 5 6 7]]
